### ISSUE TITLE
Many misuses of blockquotes

### ISSUE THREAD

**Issue by toastal** [processone/docs.ejabberd.im#131]
> The blockquote element represents a section that is quoted from
> another source.

— W3C HTML spec, https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element

One example would be [*Listen Options*](https://docs.ejabberd.im/admin/configuration/listen-options/) with a ‘quotation’ of 

> This section describes the most recent ejabberd version. If you are using an old ejabberd release, please refer to the corresponding archived version of this page in the [Archive](https://docs.ejabberd.im/archive/).

However, this is not referencing any source, internal or external.

When looking into the root of this issue, we can see Markdown is using `>` elements which are specifically for blockquotes as seen in CommonMark

> A block quote marker, optionally preceded by up to three spaces of
> indentation, consists of (a) the character `>` together with a
> following space of indentation, or (b) a single character `>` not
> followed by a space of indentation.

— CommonMark Spec v0.30, https://spec.commonmark.org/0.30/#block-quotes

`>` denotes a `<blockquote>` in Markdown and is rendered as such.

**Comment by weiss** [comment]
Did you run into an actual problem, as opposed to theoretical issues with semantically incorrect markup?

Otherwise, my 2 cent would be that this isn't an issue worth addressing. Markdown's `>` and therefore `<blockquote/>` is being used all over the world as a pragmatic solution to highlight a block of text. The reason is that Markdown-based site generators typically don't provide a usable alternative to address this use case, which in turn is due to HTML not providing an obvious alternative. Whether or not this practice is acceptable has been [discussed to death][1] for many years in many places, and I don't think this tracker is a good place to reiterate those discussions.

I tend to be pedantic myself, but the world we're living in just isn't a perfect place.

[1]: https://math.meta.stackexchange.com/questions/23015/is-using-blockquote-for-highlighting-problematic
